#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
struct TransferSignalParityCase {
    name: &'static str,
    preview_type: &'static str,
    transfer_json: &'static str,
    expected_index_status: Option<&'static str>,
    expected_filter_visible: bool,
}

const TRANSFER_SIGNAL_PARITY_CORPUS: &[TransferSignalParityCase] = &[
    TransferSignalParityCase {
        name: "suppressed_precedes_accepted",
        preview_type: "支出",
        transfer_json: r#"{"suppressed":true,"review_status":"accepted","candidate_type":"transfer"}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "resolved_none_precedes_terminal_evidence",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"none","status":"accepted","candidate_type":"transfer"}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "accepted_preserved_not_pending",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"accepted"}"#,
        expected_index_status: Some("accepted"),
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "rejected_preserved_not_pending",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"rejected"}"#,
        expected_index_status: Some("rejected"),
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "skipped_preserved_not_pending",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"skipped"}"#,
        expected_index_status: Some("skipped"),
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "auto_applied_canonicalized",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"auto_applied"}"#,
        expected_index_status: Some("accepted"),
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "auto_applied_hyphen_canonicalized",
        preview_type: "支出",
        transfer_json: r#"{"review_status":"auto-applied"}"#,
        expected_index_status: Some("accepted"),
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "explicit_pending_visible",
        preview_type: "transfer",
        transfer_json: r#"{"review_status":"pending"}"#,
        expected_index_status: Some("pending"),
        expected_filter_visible: true,
    },
    TransferSignalParityCase {
        name: "candidate_string_visible",
        preview_type: "支出",
        transfer_json: r#"{"candidate_type":"transfer"}"#,
        expected_index_status: Some("pending"),
        expected_filter_visible: true,
    },
    TransferSignalParityCase {
        name: "reason_string_visible",
        preview_type: "支出",
        transfer_json: r#"{"reason":"same amount"}"#,
        expected_index_status: Some("pending"),
        expected_filter_visible: true,
    },
    TransferSignalParityCase {
        name: "numeric_candidate_not_coerced",
        preview_type: "支出",
        transfer_json: r#"{"candidate_type":4}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "boolean_reason_not_coerced",
        preview_type: "支出",
        transfer_json: r#"{"reason":true}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "json_number_score_visible",
        preview_type: "支出",
        transfer_json: r#"{"score":0.8}"#,
        expected_index_status: Some("pending"),
        expected_filter_visible: true,
    },
    TransferSignalParityCase {
        name: "positive_decimal_score_visible",
        preview_type: "支出",
        transfer_json: r#"{"score":"0.8"}"#,
        expected_index_status: Some("pending"),
        expected_filter_visible: true,
    },
    TransferSignalParityCase {
        name: "boolean_score_not_coerced",
        preview_type: "支出",
        transfer_json: r#"{"score":true}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "container_score_not_coerced",
        preview_type: "支出",
        transfer_json: r#"{"score":[1]}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "transfer_preview_suppresses_derived",
        preview_type: "transfer",
        transfer_json: r#"{"candidate_type":"transfer"}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "chinese_transfer_preview_suppresses_derived",
        preview_type: "转账",
        transfer_json: r#"{"reason":"same amount"}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
    TransferSignalParityCase {
        name: "numeric_transfer_preview_suppresses_derived",
        preview_type: "4",
        transfer_json: r#"{"score":"1"}"#,
        expected_index_status: None,
        expected_filter_visible: false,
    },
];
