export const DEFAULT_BUDGET_ALERT_THRESHOLD = 80;
export const DEFAULT_BUDGET_ENABLED = true;
export const DEFAULT_BUDGET_FORECAST_HISTORY_PERIODS = 6;

export const BUDGET_HISTORY_CHART_CONFIG = {
    START_ANGLE: 90,
    MAX_EXECUTION_RATE: 120,
    EXECUTION_AXIS_MAX: 125,
    EXECUTION_AXIS_INTERVAL: 25,
    PRIMARY_RING_PAD_ANGLE: 3.2,
    POLAR_CENTER: ['50%', '46%'] as const,
    BAR_POLAR_RADIUS: ['20%', '74%'] as const,
    EXECUTION_POLAR_RADIUS: ['20%', '74%'] as const,
    PRIMARY_RING_RADIUS: ['80%', '86%'] as const,
    PRIMARY_LABEL_POLAR_RADIUS: ['88%', '96%'] as const,
    PRIMARY_LABEL_RADIUS_AXIS_MAX: 100,
    PRIMARY_LABEL_RADIUS_VALUE: 58,
    PRIMARY_LABEL_MIN_FONT_SIZE: 11,
    PRIMARY_LABEL_MAX_FONT_SIZE: 13,
    PRIMARY_LABEL_TRUNCATE_WIDTH: 84,
    SECONDARY_LABEL_BUFFER_INTERVAL_RATIO: 0.18,
    SECONDARY_LABEL_MAX_AXIS_RATIO: 0.93,
    BOTTOM_LABEL_FLIP_START: 210,
    BOTTOM_LABEL_FLIP_END: 330,
    AMOUNT_AXIS_LABEL_DARK_COLOR: '#888',
    AMOUNT_AXIS_LABEL_LIGHT_COLOR: '#666',
    EXECUTION_SPLIT_LINE_DARK_COLOR: 'rgba(220, 220, 220, 0.18)',
    EXECUTION_SPLIT_LINE_LIGHT_COLOR: 'rgba(79, 79, 79, 0.18)'
} as const;
