import { BUDGET_HISTORY_CHART_CONFIG } from '@/config/budget.ts';

export const {
    START_ANGLE,
    PRIMARY_RING_PAD_ANGLE,
    POLAR_CENTER,
    BAR_POLAR_RADIUS,
    PRIMARY_RING_RADIUS,
    PRIMARY_LABEL_POLAR_RADIUS,
    PRIMARY_LABEL_RADIUS_AXIS_MAX,
    PRIMARY_LABEL_RADIUS_VALUE,
    PRIMARY_LABEL_MIN_FONT_SIZE,
    PRIMARY_LABEL_MAX_FONT_SIZE,
    PRIMARY_LABEL_TRUNCATE_WIDTH,
    SECONDARY_LABEL_BUFFER_INTERVAL_RATIO,
    SECONDARY_LABEL_MAX_AXIS_RATIO,
    AMOUNT_AXIS_LABEL_DARK_COLOR,
    AMOUNT_AXIS_LABEL_LIGHT_COLOR
} = BUDGET_HISTORY_CHART_CONFIG;

export const HISTORICAL_LABEL_SERIES_Z = 8;
export const HISTORICAL_LABEL_Z2 = 40;
export const HISTORY_ANIMATION_DURATION = 720;
export const HISTORY_ANIMATION_EASING = 'cubicInOut';
export const HISTORY_LABEL_FADE_OUT_PERCENT = 0.16;
export const HISTORY_LABEL_FADE_IN_START_PERCENT = 0.68;
export const HISTORY_AMOUNT_AXIS_FADE_IN_START_PERCENT = 0.58;
export const AMOUNT_AXIS_GRID_LINE_COUNT = 4;
export const AMOUNT_AXIS_OUTER_TRANSITION_RADIUS_RATIO = 1.12;
export const AMOUNT_AXIS_MAX_RENDER_RADIUS_RATIO = 1.14;
export const SECONDARY_LABEL_MIN_PADDING_RATIO = 0.015;
export const BAR_SECTOR_WIDTH_RATIO = 0.22;
export const BAR_SECTOR_MIN_HALF_ANGLE = 2.4;
export const BAR_SECTOR_MAX_HALF_ANGLE = 7.5;
export const LABEL_ROTATION_CROSS_FADE_THRESHOLD = 90;
export const AMOUNT_AXIS_SPLIT_LINE_DARK_COLOR = 'rgba(255, 255, 255, 0.14)';
export const AMOUNT_AXIS_SPLIT_LINE_LIGHT_COLOR = 'rgba(15, 23, 42, 0.12)';
export const AMOUNT_AXIS_LABEL_OFFSET_Y = 3;
export const AMOUNT_AXIS_STATE_PREFIXES = ['grid:amount:', 'grid-label:amount:'];
export const PRIMARY_RING_FULL_CIRCLE_EPSILON = 0.8;
