use super::super::types::{EndpointOwnership, ResponseEnvelopeFamily, RuntimeState};

pub(super) const ROUTES: &[EndpointOwnership] = &[
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/enable/request",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime generates current API TOTP setup secrets and QR-code PNG data URLs for authenticated users.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/enable/confirm",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime validates TOTP setup passcodes, atomically enables 2FA with recovery codes plus a new session, and records 2fa_enabled audit details.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/disable",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime accepts the current password, operation password fallback, or step-up action tokens; atomically disables 2FA, clears recovery codes, and records 2fa_disabled audit details.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/recovery/regenerate",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime accepts the current password, operation password fallback, or step-up action tokens; replaces recovery codes and records 2fa_recovery_regenerated audit details.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/2fa/status",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime owns the authenticated 2FA status read route and the companion 2FA write management routes.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/verify",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime verifies pending_2fa action tokens plus TOTP passcodes, creates the access/refresh session, and logs login_2fa_success.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/2fa/recovery/verify",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime verifies pending_2fa action tokens plus one-time recovery codes, creates the access/refresh session, logs login_2fa_recovery_success, and records a best-effort 2fa_recovery_code_used audit log when audit_logs exists.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/security/step-up/verify",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime verifies the current password, configured operation password fallback, or 2FA TOTP passcode and issues a one-hour step_up action token for sensitive operations.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/data/export.{file_type}",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime exports authenticated user bills as CSV/TSV with the current export filename, BOM, account-name, tag-name, and filter semantics.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/data/clear/transactions",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime clears current-user bills and bill side effects after current password, configured operation password fallback, or step-up action-token verification, then records user_data audit metadata.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/data/clear/all",
        domain: "auth-security-user-data",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust auth runtime clears current-user business data after current password, configured operation password fallback, or step-up action-token verification, preserving current count keys and user_data audit metadata.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/accounts",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime lists authenticated user accounts on the non-trailing-slash route and returns frontend cents fields.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/accounts",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime creates accounts on the non-trailing-slash route with frontend cents to Postgres balance_cents conversion.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/accounts/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime lists authenticated user accounts, builds the current parent-child response hierarchy, and returns frontend cents fields; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/accounts/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime creates accounts and subaccounts with frontend cents to Postgres balance_cents conversion; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/accounts/{account_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime deletes authenticated user accounts and their direct subaccounts without fallback routing; the old accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/accounts/{account_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime reads account detail with direct subaccounts and frontend account DTO formatting; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/accounts/{account_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime updates account fields and direct subaccount sets using the authenticated user scope; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/accounts/{account_id}/transactions/clear",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime verifies the current password or operation password fallback, deletes authenticated-user account-linked bills/transfers and side effects, syncs balances, and records account audit metadata; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/accounts/{account_id}/transactions/move",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime verifies the current password or operation password fallback, moves authenticated-user account-linked bills/transfers, syncs balances, and records account audit metadata; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/accounts/display-orders",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime persists authenticated user account display ordering; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/accounts/sync-balances",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy accounts runtime recalculates authenticated user account balances from bill source/destination account links and returns the current API discrepancy report; the removed accounts route package has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/backup/",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime lists local backup files, validates zip or Fernet-encrypted archives, merges backup_records metadata, and sorts by created_at without fallback routing.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/backup/cleanup",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime applies record-first backup retention cleanup, deletes sidecar metadata, marks missing/deleted records, and writes backup_cleanup audit rows.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/backup/create",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime creates local data/ zip archives, optionally emits Fernet-encrypted .zip.enc backups, upserts backup_records, and writes backup_created audit rows.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/backup/delete/{filename}",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime safely resolves backup filenames, deletes the file and metadata sidecar, marks backup_records deleted, and writes backup_deleted audit rows.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/backup/download/{filename}",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime safely resolves local backup files and streams attachment bytes while recording backup_downloaded audit rows.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/backup/jobs",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime lists authenticated user backup job schedules from PostgreSQL backup_jobs.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/backup/jobs",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime validates and saves authenticated user backup job schedules and writes backup_job_saved audit rows.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/backup/sync",
        domain: "backup-ops",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust backup ops runtime creates a local backup, validates redacted cloud sync config, and uploads to OSS, S3, COS, Azure Blob, or WebDAV without sidecar SDK execution.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/calendar/events",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns calendar event aggregation and recurring projections; the removed calendar.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime lists authenticated user categories as the current type-keyed tree without requiring a trailing slash.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime creates parent and child categories from the frontend no-trailing-slash endpoint.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime lists authenticated user categories as the current type-keyed tree.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime creates parent and child categories with current API parentId and duplicate responses.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/categories/{category_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime deletes user-scoped categories, including parent category cascades by main category.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/{category_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime reads category details with virtual parent fallback for child categories.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/categories/{category_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime updates category fields and preserves parent rename conflict behavior.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/all",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime returns the raw user-scoped category rows for current consumers.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/categories/all",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime preserves the current batch update success response.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories/batch",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime creates preset parent/subcategory trees idempotently for the authenticated user.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/export",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime exports category JSON without generated ids or created_at values.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/flat",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime returns the current flat category DTO list.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories/import",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime imports category JSON by upserting main/subcategory rows under the current user.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories/move",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime persists category display-order updates.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/statistics",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime reads user-scoped bill category aggregates and returns the current tree-shaped category statistics response.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/categories/tree",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime serves the category tree alias.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/categories/update-all",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy categories runtime recategorizes authenticated user bills from canonical category_rules and preserves the current force flag response.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/category-rules/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime lists authenticated user canonical category rules with optional category_id and enabled_only filters; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/category-rules/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime creates canonical user-scoped rules and returns the created rule payload; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/category-rules/{rule_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime deletes canonical user-scoped rules and preserves Rule not found responses; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/category-rules/{rule_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime updates canonical user-scoped rules and returns the refreshed rule payload; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/category-rules/{rule_id}/test",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime tests a stored user-scoped rule expression against request text without mutating rule state; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/category-rules/defaults",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime creates missing built-in default daily categories and canonical rules for the authenticated user; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/category-rules/reorder",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy category-rules runtime reorders canonical user-scoped rules by request order; the removed category_rules.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/account-rules/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime lists authenticated user account recognition rules with optional account_id and enabled_only filters.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/account-rules/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime creates user-scoped account recognition rules and returns the created rule payload.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/account-rules/{rule_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime deletes user-scoped account recognition rules and preserves Rule not found responses.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/account-rules/{rule_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime updates user-scoped account recognition rules and returns the refreshed rule payload.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/account-rules/{rule_id}/test",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime tests a stored account rule against explicit parser/counterparty/payment-method/description context without mutating rule state.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/account-rules/reorder",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy account-rules runtime reorders canonical user-scoped rules after validating the requested ids are unique and owned by the current user.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/rules/overview",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy rule-center runtime aggregates user-scoped import learning rules, enabled category rule count, and recurring rule summaries without mutating rule state; the removed rule-center overview route shell has been removed.",
    },
];
