use super::super::types::{EndpointOwnership, ResponseEnvelopeFamily, RuntimeState};

pub(super) const ROUTES: &[EndpointOwnership] = &[
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/preview",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns authenticated, bounded file and session-scoped temp-file previews for generic column mapping.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/parse",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/parse_generic",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/dedup",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/confirm",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/v2/session/{session_id}",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/import/v2/session/{session_id}",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportV2Stage,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/v2/preview/{session_id}",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewAction,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/v2/preview/{session_id}/index",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewAction,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/import/v2/preview/{session_id}/selection",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewAction,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/import/v2/preview/{session_id}/update",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewAction,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/reclassify/{session_id}",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewAction,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/v2/preview-item/{preview_id}/recurring-candidates",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewItemDecision,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/import/v2/preview-item/{preview_id}/recurring-match",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewItemDecision,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/import/v2/preview-item/{preview_id}/recurring-match",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewItemDecision,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/preview-item/{preview_id}/transfer-decision",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::ImportPreviewItemDecision,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/learning/{session_id}/suggestions",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this preview-bypass route; it applies supplied preview updates and returns an explicit empty suggestion list without provider/model execution.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/v2/learning/{session_id}/suggestions",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this preview-bypass route; it validates the session and returns an explicit empty suggestion list without provider/model execution.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/v2/learning/{session_id}/promote",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this DB-write decision route and promotes stored session suggestions into import learning rules.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/import/configs",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/configs",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/configs/match",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/import/configs/suggest",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/import/configs/{config_id}",
        domain: "bills-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route; the removed bills import route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/preview-recommend",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns live LLM preview recommendation provider execution, applies yellow preview suggestions, and writes memory events without fallback routing.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/preview-recommend/accept",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LlmPreview,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route with provider-bypassed semantics; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/preview-recommend/reject",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LlmPreview,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route with provider-bypassed semantics; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/llm/memory",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LlmPreview,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns this route with provider-bypassed semantics; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/llm/config",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns effective LLM config reads, combining process-local runtime overrides with active saved configs; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/config",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns process-local LLM runtime config updates without persisting temporary provider secrets; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/llm/configs",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns saved LLM config listing with secret redaction and user scoping.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/configs",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns saved LLM config creation and active-config runtime override clearing.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/llm/configs/{config_id}",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns saved LLM config updates, preserving redacted API keys when clients send the placeholder.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/llm/configs/{config_id}",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns saved LLM config deletion with user scoping.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/configs/{config_id}/activate",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns saved LLM config activation and process-local runtime override clearing.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/llm/candidates",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns DB-backed LLM candidate listing and count filters; provider generation routes are Rust-owned.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/llm/candidates/{candidate_id}",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns single LLM candidate reads with user scoping.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/candidates/{candidate_id}/accept",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns provider-bypassed LLM candidate accept, including category-rule materialization for rule candidates.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/candidates/{candidate_id}/reject",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns provider-bypassed LLM candidate rejection.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/analyze-transactions",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns live LLM persisted transaction analysis and import-session rule induction candidate generation.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/llm/rule-synthesis",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns live LLM rule-synthesis provider execution and persists reviewable rule_synthesis candidates.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/learning/suggestions",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns global Learning Center suggestion listing, persistence, and deterministic decisions; provider-backed LLM generation is Rust-owned.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/learning/suggestions/generate",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime mines deterministic global Learning Center suggestions from import learning corpus samples; provider-backed LLM generation is Rust-owned.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/learning/suggestions/{suggestion_id}/accept",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns global Learning Center suggestion accept and rule materialization.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/learning/suggestions/batch-accept",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns global Learning Center batch suggestion accept and rule materialization.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/learning/suggestions/{suggestion_id}/reject",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns global Learning Center suggestion rejection.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/learning/rules",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns the global Learning Center rule store list contract.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/learning/rules/{rule_id}/toggle",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns the global Learning Center rule enable/disable contract.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/learning/rules/{rule_id}",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns the global Learning Center rule update contract.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/learning/rules/{rule_id}",
        domain: "ai-learning-llm",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::LearningRoute,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns the global Learning Center rule delete contract.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/ml/receipt-recognition",
        domain: "ai-ocr",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::OcrMl,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns receipt OCR recognition with disabled/cloud-stub typed errors and external tesseract provider execution.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/ml/receipt-recognition/config",
        domain: "ai-ocr",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::OcrMl,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns OCR config and receipt recognition.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/ml/receipt-recognition/config",
        domain: "ai-ocr",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::OcrMl,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust import_db_runtime owns OCR config and receipt recognition.",
    },
];
