use super::super::types::{EndpointOwnership, ResponseEnvelopeFamily, RuntimeState};

macro_rules! rust_owned_route {
    ($method:literal, $pattern:literal, $domain:literal, $envelope:expr, $notes:literal) => {
        EndpointOwnership {
            method: $method,
            pattern: $pattern,
            domain: $domain,
            state: RuntimeState::RustOwnedVerified,
            envelope: $envelope,
            deletion_blocked_until_all_import_gates: false,
            notes: $notes,
        }
    };
}

pub(super) const ROUTES: &[EndpointOwnership] = &[
    EndpointOwnership {
        method: "GET",
        pattern: "/api/insights/anomalies",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns insights anomaly detection for current-user bills; the removed insights route shell is deleted.",
    },
    rust_owned_route!(
        "GET",
        "/api/matching/bills/{bill_id}/candidates",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns formal bill candidate reads; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "GET",
        "/api/matching/bills/{bill_id}/feedback",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns formal bill feedback reads; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "GET",
        "/api/matching/candidates",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns unified session and formal bill candidate reads; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "POST",
        "/api/matching/candidates/{*candidate_id}/accept",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns candidate accept actions across formal bills and import-preview matching families; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "POST",
        "/api/matching/candidates/{*candidate_id}/clear",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns candidate clear actions for supported import-preview matching families; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "POST",
        "/api/matching/candidates/{*candidate_id}/reject",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns candidate reject actions across formal bills and import-preview matching families; the removed matching route shell is deleted."
    ),
    EndpointOwnership {
        method: "GET",
        pattern: "/api/matching/investment-settings",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::Retired,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching runtime owns the retired investment-settings endpoint and returns the deterministic 410 contract; the removed matching route shell is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/matching/investment-settings",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::Retired,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching runtime owns the retired investment-settings endpoint and returns the deterministic 410 contract; the removed matching route shell is deleted.",
    },
    rust_owned_route!(
        "POST",
        "/api/matching/manual-pair",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns manual transfer and investment pair creation for formal bills; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "GET",
        "/api/matching/pairs",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns manual pair listing for formal bills; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "DELETE",
        "/api/matching/pairs/{pair_id}",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns manual pair deletion for formal bills; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "POST",
        "/api/matching/reconcile-history",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns explicit formal bill matching history reconciliation; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "GET",
        "/api/matching/reconciliation-candidates",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns persisted import-to-formal reconciliation candidate reads; the removed matching route shell is deleted."
    ),
    rust_owned_route!(
        "GET",
        "/api/matching/sessions/{session_id}/candidates",
        "matching-recurring-calendar-networth",
        ResponseEnvelopeFamily::CurrentSuccessData,
        "Rust matching runtime owns import session candidate reads; the removed matching route shell is deleted."
    ),
    EndpointOwnership {
        method: "GET",
        pattern: "/api/networth/snapshot",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns net-worth snapshot aggregation; the removed networth.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/recurring/suggestions",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns recurring suggestion listing; the removed recurring.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/recurring/suggestions/{suggestion_id}/accept",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns recurring suggestion accept and recurring rule creation; the removed recurring.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/recurring/suggestions/{suggestion_id}/reject",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns recurring suggestion rejection; the removed recurring.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/recurring/suggestions/detect",
        domain: "matching-recurring-calendar-networth",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust matching recurring calendar networth runtime owns recurring pattern detection and suggestion persistence; the removed recurring.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/settings/bundle/export",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle export runtime returns the current user's unified JSON settings bundle with redacted LLM secrets; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/settings/bundle/import",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle import runtime applies one transaction of current-user upserts across accounts, categories, tags, templates, rules, LLM config skeletons, and OCR config; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/settings/bundle/import/preview",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle preview runtime runs the same cross-section upsert flow inside a rollback-only transaction; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/settings/bundle/sections/{section_key}/export",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle export runtime returns one non-sensitive section and preserves the current password-required response for sensitive sections; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/settings/bundle/sections/{section_key}/export",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle export runtime validates the current password before exporting sensitive LLM/OCR sections; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/settings/bundle/sections/{section_key}/import",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle section import wraps the requested section only before running current-user upsert semantics; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/settings/bundle/sections/{section_key}/import/preview",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes:
            "Rust taxonomy settings-bundle section preview wraps the requested section only and rolls back all writes; the removed settings_bundle.py route shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/tags/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns current-user tag list route and emits frontend displayOrder/hidden DTO fields; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/tags/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns current-user tag creation with current API name validation; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/tags/{tag_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns current-user tag deletion and preserves Tag not found for cross-user IDs; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/tags/{tag_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns current-user tag detail lookup; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/tags/{tag_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns tag content and visibility updates for the authenticated user; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/tags/batch",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns user-scoped tag batch creation with duplicate skip/409 semantics; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/tags/display-orders",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy runtime owns user-scoped tag display-order updates; the removed tags.py shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/templates/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime lists authenticated user bill and recurring templates with templateType filtering; the removed templates.py shell has been removed.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/templates/",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime creates authenticated user bill or recurring templates and returns the current API template DTO; the removed templates.py shell has been removed.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/templates/{template_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime deletes authenticated user templates with templateType scoping; the removed templates.py shell has been removed.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/templates/{template_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime reads authenticated user template details with templateType filtering; the removed templates.py shell has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/templates/{template_id}",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime updates authenticated user bill or recurring template fields; the removed templates.py shell has been removed.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/templates/display-orders",
        domain: "taxonomy-rules-settings",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust taxonomy templates runtime persists authenticated user template display ordering; the removed templates.py shell has been removed.",
    },
];
