use super::super::types::{EndpointOwnership, ResponseEnvelopeFamily, RuntimeState};

pub(super) const ROUTES: &[EndpointOwnership] = &[
    EndpointOwnership {
        method: "GET",
        pattern: "/api/health",
        domain: "api-runtime-shell",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RustHttpShell,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust HTTP shell health route.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/runtime",
        domain: "api-runtime-shell",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RustHttpShell,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust HTTP shell metadata route.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns core list route; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns trailing-slash list route; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns core create route with cents-to-yuan adapter semantics; the removed bills/crud_create_update.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns trailing-slash create route; the removed bills/crud_create_update.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/by-month",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns month list route; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/get",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns query get route; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/{bill_id}",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns REST get route; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/{bill_id}",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns REST update route; the removed bills/crud_create_update.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/{bill_id}",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns REST delete route; the removed bills/crud_create_update.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/modify",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns modify route; the removed bills/crud_prepare.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/delete",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns delete route; the removed bills/crud_prepare.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/batch",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns batch create route with one PostgreSQL transaction; the removed bills/crud_create_update.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/batch/update",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns batch update route; the removed bills/category_actions.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/batch/delete",
        domain: "bills-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BillsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills_crud_runtime owns batch delete route; the removed bills/category_actions.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/export",
        domain: "bills-crud-adjacent",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::RawPassthrough,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills export runtime owns CSV/XLSX file responses, current export filenames, BOM CSV output, empty-result errors, and formula-like text cell escaping; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/pictures",
        domain: "bills-crud-adjacent",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills picture runtime owns multipart transaction picture upload and data URL response semantics; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/pictures/unused",
        domain: "bills-crud-adjacent",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills picture runtime owns unused transaction picture cleanup; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/reconciliation_statements",
        domain: "bills-crud-adjacent",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills reconciliation runtime owns account statements, balance trace, filters, and current API envelopes; the removed bills/reconciliation.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/bills/{bill_id}/recurring-candidates",
        domain: "bills-recurring",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills recurring runtime owns formal bill recurring candidate generation; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/bills/{bill_id}/recurring-match",
        domain: "bills-recurring",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills recurring runtime owns recurring template binding and next-date recalculation; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/bills/{bill_id}/recurring-match",
        domain: "bills-recurring",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills recurring runtime owns recurring template unbinding and next-date recalculation; the removed bills/crud_query.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/category/quick-add-rule",
        domain: "bills-category-actions",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills category-actions runtime creates canonical category rules with the current API quick-add envelope; the removed bills/category_actions.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/bills/category/refresh",
        domain: "bills-category-actions",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust bills category-actions runtime refreshes bill categories through canonical category_rules matching; the removed bills/category_actions.py route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns core list route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns trailing-slash list route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/budgets",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns core create route with yuan-style budget amount semantics; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/budgets/",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns trailing-slash create route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/{budget_id}",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns REST get route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/budgets/{budget_id}",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns REST update route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/budgets/{budget_id}",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns REST delete route; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/export",
        domain: "budgets-crud",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_crud_runtime owns JSON export for budget rows; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/execution",
        domain: "budgets-analysis",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_execution_runtime owns budget execution aggregation; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/forecast",
        domain: "budgets-analysis",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_forecast_runtime owns historical bill aggregation, budget-map projection, forecast summary, and period-progress shape; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/budgets/history",
        domain: "budgets-history",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_history_runtime owns persisted snapshot lookup, exact-period preference, category enrichment, and on-demand fallback; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/budgets/history/snapshot",
        domain: "budgets-history",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_history_runtime owns budget_history replacement writes with canonical filter_summary and user scope; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "POST",
        pattern: "/api/budgets/import",
        domain: "budgets-import",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::BudgetsCrud,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust budgets_import_runtime owns current API array validation, per-item error accounting, and user-scoped upsert-by-name writes; the removed budgets route package is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/category-statistics",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns DB-backed category/account cents aggregation with timestamp range and keyword filtering; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/category-statistics/trends",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns monthly category/account trend buckets for bounded and all-mode ranges; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/asset-trends",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns DB-backed daily asset trend balances with 365-day bounded-range guard; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/category-pie",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns category pie aggregation for bill type/date filters; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/top-merchants",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns top merchant aggregation for date filters; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/amounts",
        domain: "statistics-read",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::StatisticsRead,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_read_runtime owns transaction amount period aggregation with CNY cents response semantics; the removed statistics read route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/overview",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns Analyzer overview report projection; the removed Analyzer route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/trends",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns Analyzer monthly/yearly trend projection; the removed Analyzer route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/comparison",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns Analyzer category comparison projection; the removed Analyzer route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/category",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns Analyzer category drilldown projection; the removed Analyzer route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/trend",
        domain: "statistics-analyzer",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessData,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics_analyzer_runtime owns Analyzer trend alias projection; the removed Analyzer route shell is deleted.",
    },
    EndpointOwnership {
        method: "GET",
        pattern: "/api/statistics/exchange-rates",
        domain: "statistics-exchange",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics exchange runtime owns provider selection, provider fallback, user custom-rate precedence, and current API result envelope; the removed exchange route shell is deleted.",
    },
    EndpointOwnership {
        method: "PUT",
        pattern: "/api/statistics/exchange-rates/custom",
        domain: "statistics-exchange",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics exchange runtime validates and persists authenticated user custom exchange rates; the removed exchange route shell is deleted.",
    },
    EndpointOwnership {
        method: "DELETE",
        pattern: "/api/statistics/exchange-rates/custom/{currency}",
        domain: "statistics-exchange",
        state: RuntimeState::RustOwnedVerified,
        envelope: ResponseEnvelopeFamily::CurrentSuccessResult,
        deletion_blocked_until_all_import_gates: false,
        notes: "Rust statistics exchange runtime deletes authenticated user custom exchange rates for the current default base currency; the removed exchange route shell is deleted.",
    },
];
