use super::types::{DecisionRequired, DomainGovernancePolicy, RuntimeBlockedStatus};

pub(super) const COVERAGE_EVIDENCE_CONTRACT: &str = "workspace.lcov";
pub(super) const EMPTY_STRINGS: &[&str] = &[];
pub(super) const POSTGRES_DB_INVARIANT_IDS: &[&str] = &[
    "postgres_authority",
    "referential_integrity",
    "rollback_on_error",
    "positive_user_scope",
    "amount_units",
    "time_normalization",
];
pub(super) const IMPORT_DB_INVARIANT_IDS: &[&str] = &[
    "postgres_authority",
    "referential_integrity",
    "single_writer",
    "transactional_staging",
    "rollback_on_error",
    "positive_user_scope",
    "amount_units",
    "time_normalization",
];
pub(super) const ROUTE_MATRIX_ONLY_EVIDENCE: &[&str] = &["route_matrix"];
pub(super) const RUNTIME_METADATA_EVIDENCE: &[&str] = &["route_matrix", "runtime_metadata"];
pub(super) const DB_RUNTIME_EVIDENCE: &[&str] = &["route_matrix", "db_smoke"];
pub(super) const DB_SCHEMA_EVIDENCE: &[&str] = &["db_smoke", "schema_contract"];
pub(super) const DB_REPOSITORY_EVIDENCE: &[&str] = &["db_smoke", "repository_contract"];
pub(super) const FRONTEND_DB_EVIDENCE: &[&str] = &["route_matrix", "db_smoke", "frontend_contract"];
pub(super) const FULL_ROUTE_EVIDENCE: &[&str] = &[
    "route_matrix",
    "golden_fixture",
    "db_smoke",
    "frontend_contract",
];
pub(super) const FULL_ROUTE_EVIDENCE_NO_FIXTURE: &[&str] =
    &["route_matrix", "db_smoke", "frontend_contract"];
pub(super) const PROVIDER_ROUTE_EVIDENCE: &[&str] = &["route_matrix", "provider_parity"];
pub(super) const AUTH_TOKEN_DELETION_BLOCKERS: &[&str] = EMPTY_STRINGS;
pub(super) const TAXONOMY_DELETION_BLOCKERS: &[&str] = EMPTY_STRINGS;

pub(super) const DOMAIN_GOVERNANCE_POLICIES: &[DomainGovernancePolicy] = &[
    DomainGovernancePolicy {
        domain: "api-runtime-shell",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/router.rs",
            "src/backend/http/server.rs",
            "src/backend/http/runtime.rs",
        ],
        tests_verified: &[
            "tests/backend/core/import_pipeline_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: EMPTY_STRINGS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: RUNTIME_METADATA_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "bills-import",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/import_routes/mod.rs",
            "src/backend/db/import_staging.rs",
            "src/backend/core/import_pipeline.rs",
            "src/backend/parsers/lib.rs",
        ],
        tests_verified: &[
            "tests/backend/core/import_pipeline_contracts.rs",
            "tests/backend/db/vector_outbox.rs",
            "tests/backend/parsers/parser_contracts.rs",
        ],
        fixtures: &["tests/backend/parsers/fixtures/parser_golden_contracts.json"],
        db_invariant_ids: IMPORT_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "The removed bills import route package has been removed; current core import services remain only as preserved sidecar/support code for matching, provider, and global learning ownership.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "ai-learning-llm",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/import_routes/mod.rs",
            "src/backend/http/import_routes/ai_response_contract.rs",
            "src/backend/core/ai_ocr_llm/mod.rs",
            "src/backend/core/ai_ocr_llm/llm_config.rs",
            "src/backend/core/ai_ocr_llm/llm_prompts.rs",
            "src/backend/core/ai_ocr_llm/llm_provider.rs",
            "src/backend/core/import_learning.rs",
        ],
        tests_verified: &[
            "tests/backend/core/ai_ocr_llm_contracts.rs",
            "tests/backend/core/import_learning_contracts.rs",
            "tests/backend/core/import_pipeline_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: IMPORT_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Live provider-backed preview recommendation generation, transaction analysis, and rule synthesis remain external-provider-owned; global Learning Center suggestions and rules are Rust-owned.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: PROVIDER_ROUTE_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "ai-ocr",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/import_routes/mod.rs",
            "src/backend/core/ai_ocr_llm/mod.rs",
            "src/backend/core/ai_ocr_llm/ocr_config.rs",
            "src/backend/core/ai_ocr_llm/ocr_parser.rs",
            "src/backend/db/app_settings.rs",
        ],
        tests_verified: &[
            "tests/backend/core/ai_ocr_llm_contracts.rs",
            "tests/backend/core/import_pipeline_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: IMPORT_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Rust owns receipt OCR config and recognition. The tesseract provider uses an external tesseract binary through stdin/stdout and returns provider_unconfigured when the binary or cloud provider is unavailable.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE_NO_FIXTURE,
    },
    DomainGovernancePolicy {
        domain: "bills-crud",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/bill_routes/",
            "src/backend/db/bills.rs",
            "src/backend/core/adapters/transaction.rs",
        ],
        tests_verified: &[
            "tests/backend/core/transaction_adapter_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FRONTEND_DB_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "bills-crud-adjacent",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/bill_routes/",
            "src/backend/core/adapters/transaction.rs",
            "src/backend/core/matching.rs",
            "src/backend/core/ops.rs",
        ],
        tests_verified: &[
            "tests/backend/core/transaction_adapter_contracts.rs",
            "tests/backend/core/matching_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "bills-recurring",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/bill_routes/",
            "src/backend/db/bills.rs",
        ],
        tests_verified: &[
            "tests/backend/core/transaction_adapter_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "bills-category-actions",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/bill_routes/",
            "src/backend/core/category_rules/mod.rs",
            "src/backend/core/matching.rs",
        ],
        tests_verified: &[
            "tests/backend/core/transaction_adapter_contracts.rs",
            "tests/backend/core/bridge_cli_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "budgets-crud",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/budget_routes.rs",
            "src/backend/db/budgets.rs",
            "src/backend/core/budgets.rs",
        ],
        tests_verified: &[
            "tests/backend/core/budget_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "The removed budgets route package has been removed; Rust budgets_crud_runtime remains the runtime owner.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FRONTEND_DB_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "budgets-analysis",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/budget_routes.rs",
            "src/backend/db/budgets.rs",
            "src/backend/core/budgets.rs",
        ],
        tests_verified: &[
            "tests/backend/core/budget_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "The removed budgets route package has been removed; Rust budgets_analysis_runtime remains the runtime owner.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "budgets-history",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/budget_routes.rs",
            "src/backend/db/budgets.rs",
            "src/backend/core/budgets.rs",
        ],
        tests_verified: &[
            "tests/backend/core/budget_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "The removed budgets route package has been removed; Rust budgets_history_runtime remains the runtime owner.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "budgets-import",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/budget_routes.rs",
            "src/backend/db/budgets.rs",
            "src/backend/core/budgets.rs",
        ],
        tests_verified: &[
            "tests/backend/core/budget_contracts.rs",
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "The removed budgets route package has been removed; Rust budgets_import_runtime remains the runtime owner.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE_NO_FIXTURE,
    },
    DomainGovernancePolicy {
        domain: "statistics-read",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/statistics_routes/mod.rs",
            "src/backend/db/statistics.rs",
            "src/backend/core/statistics.rs",
        ],
        tests_verified: &[
            "tests/backend/core/statistics_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "The removed statistics read route shell has been removed; Analyzer overview/trends/comparison/category/trend remain governed by statistics-analyzer.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE_NO_FIXTURE,
    },
    DomainGovernancePolicy {
        domain: "statistics-analyzer",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/statistics_routes/mod.rs",
            "src/backend/db/statistics.rs",
            "src/backend/core/statistics.rs",
        ],
        tests_verified: &[
            "tests/backend/core/statistics_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "The removed statistics Analyzer and insights route shells have been removed; Analyzer report data, chart-plan contract, and insights anomaly detection are Rust-owned. Net worth remains governed by matching-recurring-calendar-networth.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE_NO_FIXTURE,
    },
    DomainGovernancePolicy {
        domain: "statistics-exchange",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/statistics_routes/mod.rs",
            "src/backend/core/statistics.rs",
            "src/backend/db/statistics.rs",
        ],
        tests_verified: &[
            "tests/backend/core/statistics_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior: "The removed statistics exchange route shell has been removed.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: FULL_ROUTE_EVIDENCE_NO_FIXTURE,
    },
    DomainGovernancePolicy {
        domain: "auth-security-user-data",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/auth_routes/mod.rs",
            "src/backend/db/auth.rs",
            "src/backend/db/auth_registration.rs",
            "src/backend/db/user_data.rs",
            "src/backend/core/auth/mod.rs",
        ],
        tests_verified: &[
            "tests/backend/core/auth_security_contracts.rs",
            "tests/backend/core/ops_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: EMPTY_STRINGS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Login, registration, token session list/revoke, API/MCP personal token generation, refresh token exchange, logout, account recovery email verification/resend/password forgot/reset, OAuth2 callback authorize disabled-safe/not-implemented response, profile, avatar, profile cloud settings, profile external-auth list/unlink, profile verification-email resend, system version, user-data statistics, user-data CSV/TSV export, destructive user-data clear, authenticated 2FA status, TOTP login verification, recovery-code login verification, 2FA write management, and step-up verification routes are Rust-owned; OAuth2 provider exchange is explicitly disabled-safe/not-implemented in the current workspace build.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_RUNTIME_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "taxonomy-rules-settings",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/taxonomy_routes/mod.rs",            "src/backend/core/adapters/category.rs",
            "src/backend/db/taxonomy",
        ],
        tests_verified: &["tests/backend/core/runtime_governance_contracts.rs"],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: EMPTY_STRINGS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: TAXONOMY_DELETION_BLOCKERS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Account CRUD/display-order/balance sync/transaction move-clear, account-rule list/create/update/delete/reorder/test, tag CRUD/display-order/batch-create, category master-data/statistics/update-all, category-rule list/create/update/delete/reorder/defaults/test, rule overview, templates, and settings bundle import/preview/export routes are Rust-owned; all removed taxonomy route shells have been removed.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: ROUTE_MATRIX_ONLY_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "matching-recurring-calendar-networth",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/matching_routes.rs",
            "src/backend/db/matching.rs",
            "src/backend/db/recurring.rs",
            "src/backend/db/statistics.rs",            "src/backend/core/matching.rs",
            "src/backend/core/statistics.rs",
        ],
        tests_verified: &[
            "tests/backend/core/matching_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: EMPTY_STRINGS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Formal matching candidates, feedback, manual pairs, candidate actions, reconcile history, retired investment settings, recurring suggestions, calendar, and net worth runtime routes are Rust-owned; the removed matching, recurring, calendar, and networth route shells have been removed.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: ROUTE_MATRIX_ONLY_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "backup-ops",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/http/backup_routes/mod.rs",
            "src/backend/http/backup_sync.rs",
            "src/backend/core/ops.rs",
            "src/backend/db/backup.rs",
        ],
        tests_verified: &[
            "tests/backend/core/ops_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: EMPTY_STRINGS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Backup file list/create/download/delete/cleanup, jobs, and cloud sync provider runtime routes are Rust-owned; restore and history recovery routes are intentionally absent.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: ROUTE_MATRIX_ONLY_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "database-schema",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/db/postgres.rs",
            "src/backend/db/postgres/migrations",
            "src/backend/db/runtime.rs",
        ],
        tests_verified: &[
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Rust now owns PostgreSQL foundational schema initialization and core user-scoped constraints; non-Postgres schema/migration/recovery paths are absent.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_SCHEMA_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "database-repositories",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/db/bills.rs",
            "src/backend/db/budgets.rs",
            "src/backend/db/import_staging.rs",
            "src/backend/db/auth.rs",
            "src/backend/db/statistics.rs",
            "src/backend/db/app_settings.rs",
            "src/backend/db/taxonomy",
        ],
        tests_verified: &["tests/backend/db/vector_outbox.rs"],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: POSTGRES_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "Repository implementations are PostgreSQL-only across Rust-owned domains; non-Postgres repository, recovery, and migration facades are absent.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: DB_REPOSITORY_EVIDENCE,
    },
    DomainGovernancePolicy {
        domain: "database-facade",
        retired_source_files: EMPTY_STRINGS,
        rust_owner_files: &[
            "src/backend/core/runtime_governance/mod.rs",
            "src/backend/db/runtime.rs",
            "src/backend/db/postgres.rs",
        ],
        tests_verified: &[
            "tests/backend/core/runtime_governance_contracts.rs",
        ],
        fixtures: EMPTY_STRINGS,
        db_invariant_ids: IMPORT_DB_INVARIANT_IDS,
        coverage_evidence: COVERAGE_EVIDENCE_CONTRACT,
        deletion_blockers: EMPTY_STRINGS,
        blocked_status: RuntimeBlockedStatus::None,
        unsupported_behavior:
            "The database-facade contract is governance-only and does not, by itself, operate on removed runtime entry points.",
        decision_required: DecisionRequired::None,
        decision_owner: "none",
        transition_evidence: ROUTE_MATRIX_ONLY_EVIDENCE,
    },
];
