"""Bills domain constants and heuristic thresholds."""

from __future__ import annotations

ALLOWED_BILLS_FILE_EXTENSIONS = frozenset({"csv", "xlsx", "xls", "txt"})
ALLOWED_BILLS_PICTURE_EXTENSIONS = frozenset({"png", "jpg", "jpeg", "gif", "webp", "bmp"})
MAX_BILLS_FILE_SIZE = 10 * 1024 * 1024

IMPORT_CONFIG_BASE_WEIGHT = 3.0
IMPORT_CONFIG_USE_COUNT_CAP = 20.0
IMPORT_CONFIG_USE_COUNT_FACTOR = 0.1

IMPORT_HEADER_STRONG_EXACT_SCORE = 12.0
IMPORT_HEADER_EXACT_SCORE = 10.0
IMPORT_HEADER_SEMANTIC_MEDIUM_SCORE = 9.5
IMPORT_HEADER_SEMANTIC_SCORE = 9.0
IMPORT_HEADER_TYPE_HINT_SCORE = 8.0
IMPORT_HEADER_CONTEXT_SCORE = 7.0
IMPORT_HEADER_PARTIAL_SCORE = 6.0
IMPORT_HEADER_CANDIDATE_MIN_SCORE = 5.0

IMPORT_HEADER_MATCH_UNIQUE_BONUS = 2.5
IMPORT_HEADER_MATCH_REPEAT_BONUS = 0.5
IMPORT_HEADER_MATCHED_TYPES_WEIGHT = 3.0
IMPORT_HEADER_NON_EMPTY_CELL_WEIGHT = 0.5
IMPORT_HEADER_NON_EMPTY_CELL_CAP = 6
IMPORT_HEADER_DATA_LIKE_PENALTY = 2.0
IMPORT_HEADER_LOW_MATCH_TYPES_PENALTY = 6.0
IMPORT_HEADER_MIN_MATCHED_TYPES = 2
IMPORT_HEADER_MIN_REVIEW_SCORE = 8.0
IMPORT_HEADER_ACCEPT_SCORE = 10.0
IMPORT_HEADER_SCAN_LIMIT = 30
IMPORT_HEADER_NEXT_ROW_SCORE_CAP = 4.0
IMPORT_HEADER_NEXT_ROW_WEIGHT = 1.5
