pub(crate) const STANDARD_DAILY_V1_ACCOUNT_RULES: &[DefaultAccountRule] = &[
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:cash",
        account_name: "现金",
        rule_expression: "OR={现金,现钞}",
        priority: 100,
        source_key: "standard_daily_v1:account:cash",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:bank-card",
        account_name: "银行卡",
        rule_expression: "OR={银行卡,储蓄卡,借记卡,银联,快捷支付,网银,手机银行}+NOT={信用卡,花呗}",
        priority: 110,
        source_key: "standard_daily_v1:account:bank-card",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:credit-card",
        account_name: "信用卡",
        rule_expression: "OR={信用卡,贷记卡}",
        priority: 120,
        source_key: "standard_daily_v1:account:credit-card",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:wechat",
        account_name: "微信",
        rule_expression: "OR={微信支付,财付通,微信零钱,零钱通,微信红包}",
        priority: 130,
        source_key: "standard_daily_v1:account:wechat",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:alipay",
        account_name: "支付宝",
        rule_expression: "OR={支付宝,余额宝,支付宝余额}+NOT={花呗}",
        priority: 140,
        source_key: "standard_daily_v1:account:alipay",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:consumer-credit",
        account_name: "花呗/消费信贷",
        rule_expression: "OR={花呗,白条,消费贷,分期}",
        priority: 150,
        source_key: "standard_daily_v1:account:consumer-credit",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:investment",
        account_name: "理财/投资账户",
        rule_expression: "OR={理财,基金,证券,股票,债券,黄金,贵金属}",
        priority: 160,
        source_key: "standard_daily_v1:account:investment",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:receivable",
        account_name: "应收款",
        rule_expression: "OR={应收,借出,待收,收款}",
        priority: 170,
        source_key: "standard_daily_v1:account:receivable",
    },
    DefaultAccountRule {
        name: "default:standard_daily_v1:account:payable",
        account_name: "应付款/借款",
        rule_expression: "OR={应付,借入,借款,待还}",
        priority: 180,
        source_key: "standard_daily_v1:account:payable",
    },
];
