pub(crate) const STANDARD_DAILY_V1_ACCOUNTS: &[DefaultAccount] = &[
    DefaultAccount {
        name: "现金",
        category: ACCOUNT_CASH,
        account_type: ACCOUNT_SINGLE,
        icon: "1",
        color: "000000",
        display_order: 0,
    },
    DefaultAccount {
        name: "银行卡",
        category: ACCOUNT_BANK_CARD,
        account_type: ACCOUNT_SINGLE,
        icon: "100",
        color: "0a84ff",
        display_order: 1,
    },
    DefaultAccount {
        name: "信用卡",
        category: ACCOUNT_CREDIT_CARD,
        account_type: ACCOUNT_SINGLE,
        icon: "100",
        color: "ff9500",
        display_order: 2,
    },
    DefaultAccount {
        name: "微信",
        category: ACCOUNT_VIRTUAL,
        account_type: ACCOUNT_SINGLE,
        icon: "500",
        color: "30d158",
        display_order: 3,
    },
    DefaultAccount {
        name: "支付宝",
        category: ACCOUNT_VIRTUAL,
        account_type: ACCOUNT_SINGLE,
        icon: "500",
        color: "0a84ff",
        display_order: 4,
    },
    DefaultAccount {
        name: "花呗/消费信贷",
        category: ACCOUNT_DEBT,
        account_type: ACCOUNT_SINGLE,
        icon: "600",
        color: "ff453a",
        display_order: 5,
    },
    DefaultAccount {
        name: "理财/投资账户",
        category: ACCOUNT_INVESTMENT,
        account_type: ACCOUNT_SINGLE,
        icon: "800",
        color: "34c759",
        display_order: 6,
    },
    DefaultAccount {
        name: "应收款",
        category: ACCOUNT_RECEIVABLE,
        account_type: ACCOUNT_SINGLE,
        icon: "700",
        color: "30d158",
        display_order: 7,
    },
    DefaultAccount {
        name: "应付款/借款",
        category: ACCOUNT_DEBT,
        account_type: ACCOUNT_SINGLE,
        icon: "600",
        color: "ff9f0a",
        display_order: 8,
    },
];
