pub(crate) const STANDARD_DAILY_V1_CATEGORY_RULES: &[DefaultCategoryRule] = &[
    DefaultCategoryRule {
        name: "default:standard_daily_v1:餐饮食品/外卖",
        main_category: "餐饮食品",
        sub_category: "外卖",
        rule_expression: "OR={美团外卖,饿了么,外卖,外卖订单}+NOT={退款,返现}",
        priority: 100,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:餐饮食品/餐馆",
        main_category: "餐饮食品",
        sub_category: "餐馆",
        rule_expression: "OR={餐饮,餐厅,饭店,小吃,烧烤,火锅,咖啡,奶茶,茶饮,肯德基,麦当劳,必胜客,瑞幸,星巴克}+NOT={退款}",
        priority: 110,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:餐饮食品/食材水果",
        main_category: "餐饮食品",
        sub_category: "食材水果",
        rule_expression: "OR={超市,菜市场,生鲜,水果,蔬菜,买菜,便利店,盒马,叮咚买菜,朴朴,钱大妈}+NOT={退款}",
        priority: 120,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:购物衣物/网购",
        main_category: "购物衣物",
        sub_category: "网购",
        rule_expression: "OR={淘宝,天猫,京东,拼多多,抖音电商,快手小店,小红书,唯品会,苏宁}+NOT={退款,退货}",
        priority: 200,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:购物衣物/快递物流",
        main_category: "购物衣物",
        sub_category: "快递物流",
        rule_expression: "OR={快递,顺丰,中通,圆通,韵达,邮政,丰巢,菜鸟驿站}",
        priority: 210,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:居住水电/房租房贷",
        main_category: "居住水电",
        sub_category: "房租房贷",
        rule_expression: "OR={房租,租金,房贷,按揭,住房贷款}",
        priority: 300,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:居住水电/水电燃气",
        main_category: "居住水电",
        sub_category: "水电燃气",
        rule_expression: "OR={水费,电费,燃气,煤气,供暖,宽带缴费}",
        priority: 310,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:居住水电/物业管理",
        main_category: "居住水电",
        sub_category: "物业管理",
        rule_expression: "OR={物业,物业费,停车管理费}",
        priority: 320,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:交通通信/公共交通",
        main_category: "交通通信",
        sub_category: "公共交通",
        rule_expression: "OR={地铁,公交,公交车,轨道交通,交通卡}",
        priority: 400,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:交通通信/打车",
        main_category: "交通通信",
        sub_category: "打车",
        rule_expression: "OR={滴滴,高德打车,T3出行,网约车,出租车}",
        priority: 410,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:交通通信/长途出行",
        main_category: "交通通信",
        sub_category: "长途出行",
        rule_expression: "OR={高铁,火车,机票,航空,机场,客运,船票}",
        priority: 420,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:交通通信/停车加油",
        main_category: "交通通信",
        sub_category: "停车加油",
        rule_expression: "OR={停车,停车费,加油,充电桩,高速,ETC}",
        priority: 430,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:交通通信/通讯服务",
        main_category: "交通通信",
        sub_category: "通讯服务",
        rule_expression: "OR={话费,流量,手机费,宽带费,通讯费}+NOT={退款}",
        priority: 440,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:生活服务/美容美发",
        main_category: "生活服务",
        sub_category: "美容美发",
        rule_expression: "OR={美容,美发,理发,美甲,护肤}",
        priority: 500,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:生活服务/洗护维修",
        main_category: "生活服务",
        sub_category: "洗护维修",
        rule_expression: "OR={洗衣,干洗,维修,开锁,修理,保养}",
        priority: 510,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:医疗健康/药品就医",
        main_category: "医疗健康",
        sub_category: "药品就医",
        rule_expression: "OR={医院,门诊,药店,医保,挂号,药品,处方}",
        priority: 600,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:医疗健康/体检牙科",
        main_category: "医疗健康",
        sub_category: "体检牙科",
        rule_expression: "OR={体检,牙科,口腔,洗牙}",
        priority: 610,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:教育学习/学费培训",
        main_category: "教育学习",
        sub_category: "学费培训",
        rule_expression: "OR={学费,培训,课程,补习,托管,幼儿园}",
        priority: 700,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:教育学习/书籍文具",
        main_category: "教育学习",
        sub_category: "书籍文具",
        rule_expression: "OR={书店,图书,教材,文具,打印,复印}",
        priority: 710,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:文化娱乐/影视音乐",
        main_category: "文化娱乐",
        sub_category: "影视音乐",
        rule_expression: "OR={电影,影院,视频会员,音乐会员,演出,票务}",
        priority: 800,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:文化娱乐/游戏",
        main_category: "文化娱乐",
        sub_category: "游戏",
        rule_expression: "OR={游戏,手游,主机游戏,点券,皮肤}",
        priority: 810,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:文化娱乐/旅游度假",
        main_category: "文化娱乐",
        sub_category: "旅游度假",
        rule_expression: "OR={旅游,酒店,民宿,景区,门票,度假}",
        priority: 820,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:人情社交/红包转账",
        main_category: "人情社交",
        sub_category: "红包转账",
        rule_expression: "OR={红包,转账红包,收红包,发红包}",
        priority: 900,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:人情社交/礼品随礼",
        main_category: "人情社交",
        sub_category: "礼品随礼",
        rule_expression: "OR={礼品,礼物,随礼,礼金,份子钱,结婚红包}",
        priority: 910,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:金融保险税费/保险",
        main_category: "金融保险税费",
        sub_category: "保险",
        rule_expression: "OR={保险,保费,车险,医保缴费}",
        priority: 1000,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:金融保险税费/手续费",
        main_category: "金融保险税费",
        sub_category: "手续费",
        rule_expression: "OR={手续费,服务费,年费,管理费}",
        priority: 1010,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:金融保险税费/税费社保公积金",
        main_category: "金融保险税费",
        sub_category: "税费社保公积金",
        rule_expression: "OR={个税,税费,社保,公积金}",
        priority: 1020,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:借贷往来/还款",
        main_category: "借贷往来",
        sub_category: "还款",
        rule_expression: "OR={借款还款,还借款,还钱,归还借款}+NOT={信用卡}",
        priority: 1100,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:职业收入/工资",
        main_category: "职业收入",
        sub_category: "工资",
        rule_expression: "REGEX={(工资|薪资|薪金|代发工资)}",
        priority: 2000,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:职业收入/奖金兼职报销",
        main_category: "职业收入",
        sub_category: "奖金",
        rule_expression: "OR={奖金,年终奖,绩效,兼职,劳务费,报销,补贴}+NOT={退款}",
        priority: 2010,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:投资收入/收益",
        main_category: "投资收入",
        sub_category: "理财收益",
        rule_expression: "OR={利息,分红,理财收益,收益到账}",
        priority: 2100,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:其他收入/退款",
        main_category: "其他收入",
        sub_category: "退款",
        rule_expression: "OR={退款,退货,冲正,返现,退票}",
        priority: 2200,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:账户互转/信用卡还款",
        main_category: "账户互转",
        sub_category: "信用卡还款",
        rule_expression: "OR={信用卡还款,还信用卡,自动还款}",
        priority: 3000,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:账户互转/银行卡互转",
        main_category: "账户互转",
        sub_category: "银行卡互转",
        rule_expression: "OR={跨行转账,银行卡转账,快捷转账}+NOT={红包,礼金,工资,退款}",
        priority: 3010,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:账户互转/支付账户互转",
        main_category: "账户互转",
        sub_category: "支付账户互转",
        rule_expression: "OR={余额提现,充值,提现到银行卡,微信零钱提现,支付宝提现}",
        priority: 3020,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:投资理财/金融理财",
        main_category: "投资理财",
        sub_category: "金融理财",
        rule_expression: "OR={理财,基金,证券,股票,债券}+NOT={退款}",
        priority: 4000,
    },
    DefaultCategoryRule {
        name: "default:standard_daily_v1:投资理财/黄金贵金属",
        main_category: "投资理财",
        sub_category: "黄金贵金属",
        rule_expression: "OR={黄金,贵金属}+NOT={礼品,首饰}",
        priority: 4010,
    },
];
