pub(crate) const STANDARD_DAILY_V1_CATEGORIES: &[DefaultCategory] = &[
    DefaultCategory {
        type_code: EXPENSE,
        name: "餐饮食品",
        icon: "1",
        color: "ff6b22",
        priority: 100,
        sub_categories: FOOD_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "购物衣物",
        icon: "300",
        color: "af52de",
        priority: 200,
        sub_categories: SHOPPING_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "居住水电",
        icon: "400",
        color: "34c759",
        priority: 300,
        sub_categories: HOUSING_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "交通通信",
        icon: "500",
        color: "007aff",
        priority: 400,
        sub_categories: TRANSPORT_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "生活服务",
        icon: "600",
        color: "64d2ff",
        priority: 500,
        sub_categories: DAILY_SERVICE_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "医疗健康",
        icon: "700",
        color: "ff453a",
        priority: 600,
        sub_categories: HEALTH_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "教育学习",
        icon: "800",
        color: "5856d6",
        priority: 700,
        sub_categories: EDUCATION_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "文化娱乐",
        icon: "900",
        color: "ff2d55",
        priority: 800,
        sub_categories: ENTERTAINMENT_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "人情社交",
        icon: "910",
        color: "ff453a",
        priority: 900,
        sub_categories: SOCIAL_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "金融保险税费",
        icon: "980",
        color: "30d158",
        priority: 1000,
        sub_categories: FINANCE_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "借贷往来",
        icon: "990",
        color: "ff9500",
        priority: 1100,
        sub_categories: BORROWING_SUBS,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "其他支出",
        icon: "1000",
        color: "8e8e93",
        priority: 1200,
        sub_categories: OTHER_EXPENSE_SUBS,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "职业收入",
        icon: "2000",
        color: "30d158",
        priority: 2000,
        sub_categories: JOB_INCOME_SUBS,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "投资收入",
        icon: "2020",
        color: "34c759",
        priority: 2100,
        sub_categories: INVESTMENT_INCOME_SUBS,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "其他收入",
        icon: "2030",
        color: "4cd964",
        priority: 2200,
        sub_categories: OTHER_INCOME_SUBS,
    },
    DefaultCategory {
        type_code: TRANSFER,
        name: "账户互转",
        icon: "4000",
        color: "2196f3",
        priority: 3000,
        sub_categories: TRANSFER_SUBS,
    },
    DefaultCategory {
        type_code: INVESTMENT,
        name: "投资理财",
        icon: "5000",
        color: "34c759",
        priority: 4000,
        sub_categories: INVESTMENT_SUBS,
    },
];
