"""Shared LLM learning service limits and defaults."""

_MAX_ANALYZE_LIMIT = 20
_MAX_SESSION_SELECTION = 20
_MAX_SESSION_CATEGORY_GROUPS = 10
_MAX_PREVIEW_UPDATE_BATCH = 20
_MAX_RULE_SYNTHESIS_GROUPS = 8
_MAX_RULE_SYNTHESIS_EVIDENCE = 4
_DEFAULT_TEMPERATURE = 0.3
_DEFAULT_MAX_TOKENS = 4096
