// 中文导读：SQLite repository 层，负责 schema、事务、user-scope 查询、row helper 和跨表写入边界。
// 维护重点：SQL 与数据行映射集中在本层，HTTP handler 不应复制查询逻辑或绕过事务 helper。
// 不变式：业务写入默认 rollback-on-error，审计与兼容缓存只有在注释明确时才能作为 best-effort。

const DEFAULT_DAILY_CATEGORIES: &[DefaultCategory] = &[
    DefaultCategory {
        type_code: EXPENSE,
        name: "餐饮",
        icon: "1",
        color: "ff6b22",
        priority: 100,
        sub_categories: CAT_DINING,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "食品日用",
        icon: "210",
        color: "4caf50",
        priority: 200,
        sub_categories: CAT_GROCERY,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "居住家庭",
        icon: "200",
        color: "607d8b",
        priority: 300,
        sub_categories: CAT_HOUSING,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "交通出行",
        icon: "300",
        color: "009688",
        priority: 400,
        sub_categories: CAT_TRANSPORT,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "医疗健康",
        icon: "800",
        color: "ff3b30",
        priority: 500,
        sub_categories: CAT_HEALTH,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "服饰美妆",
        icon: "100",
        color: "673ab7",
        priority: 600,
        sub_categories: CAT_FASHION,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "数码办公",
        icon: "230",
        color: "3f51b5",
        priority: 700,
        sub_categories: CAT_DIGITAL,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "教育成长",
        icon: "600",
        color: "cddc39",
        priority: 800,
        sub_categories: CAT_EDUCATION,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "娱乐休闲",
        icon: "500",
        color: "ff2d55",
        priority: 900,
        sub_categories: CAT_ENTERTAINMENT,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "旅行住宿",
        icon: "590",
        color: "00bcd4",
        priority: 1000,
        sub_categories: CAT_TRAVEL,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "人情社交",
        icon: "700",
        color: "4cd964",
        priority: 1100,
        sub_categories: CAT_SOCIAL,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "金融保险",
        icon: "900",
        color: "ff9500",
        priority: 1200,
        sub_categories: CAT_FINANCE,
    },
    DefaultCategory {
        type_code: EXPENSE,
        name: "其他支出",
        icon: "1000",
        color: "8e8e93",
        priority: 1300,
        sub_categories: CAT_OTHER_EXPENSE,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "工作收入",
        icon: "2000",
        color: "ff6b22",
        priority: 2000,
        sub_categories: CAT_WORK_INCOME,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "经营收入",
        icon: "2080",
        color: "4caf50",
        priority: 2100,
        sub_categories: CAT_BUSINESS_INCOME,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "投资收益",
        icon: "2100",
        color: "ff9500",
        priority: 2200,
        sub_categories: CAT_INVESTMENT_INCOME,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "生活收入",
        icon: "710",
        color: "4cd964",
        priority: 2300,
        sub_categories: CAT_LIFE_INCOME,
    },
    DefaultCategory {
        type_code: INCOME,
        name: "其他收入",
        icon: "1000",
        color: "8e8e93",
        priority: 2400,
        sub_categories: CAT_OTHER_INCOME,
    },
    DefaultCategory {
        type_code: TRANSFER,
        name: "账户互转",
        icon: "4000",
        color: "2196f3",
        priority: 3000,
        sub_categories: CAT_TRANSFER,
    },
];

const DEFAULT_DAILY_CATEGORY_RULES: &[DefaultCategoryRule] = &[
    DefaultCategoryRule { name: "default:餐饮/外卖", main_category: "餐饮", sub_category: "外卖", rule_expression: "(OR={美团外卖,饿了么,外卖,饭团}/REGEX={(美团|饿了么).*(外卖|订单)})+NOT={退款,退货,取消,冲正}", priority: 100 },
    DefaultCategoryRule { name: "default:餐饮/咖啡奶茶", main_category: "餐饮", sub_category: "咖啡奶茶", rule_expression: "OR={瑞幸,星巴克,库迪,奈雪,喜茶,蜜雪冰城,霸王茶姬,沪上阿姨,茶百道,咖啡,奶茶}", priority: 110 },
    DefaultCategoryRule { name: "default:餐饮/早餐", main_category: "餐饮", sub_category: "早餐", rule_expression: "REGEX={(早餐|早饭|包子|豆浆|油条|粥店)}", priority: 120 },
    DefaultCategoryRule { name: "default:食品日用/超市便利", main_category: "食品日用", sub_category: "超市便利", rule_expression: "OR={盒马,山姆,沃尔玛,永辉,华润万家,便利蜂,罗森,全家,7-11,超市,便利店}", priority: 200 },
    DefaultCategoryRule { name: "default:食品日用/菜场生鲜", main_category: "食品日用", sub_category: "菜场生鲜", rule_expression: "OR={叮咚买菜,朴朴,每日优鲜,菜市场,生鲜,水果,蔬菜,肉铺}", priority: 210 },
    DefaultCategoryRule { name: "default:居住家庭/水费", main_category: "居住家庭", sub_category: "水费", rule_expression: "OR={自来水,水务}/REGEX={水费}", priority: 300 },
    DefaultCategoryRule { name: "default:居住家庭/电费", main_category: "居住家庭", sub_category: "电费", rule_expression: "OR={国家电网,南方电网,供电}/REGEX={电费}", priority: 310 },
    DefaultCategoryRule { name: "default:居住家庭/燃气", main_category: "居住家庭", sub_category: "燃气", rule_expression: "OR={燃气,天然气,煤气}", priority: 320 },
    DefaultCategoryRule { name: "default:居住家庭/房租", main_category: "居住家庭", sub_category: "房租", rule_expression: "(OR={房租,租金,公寓}/REGEX={(房租|租金).*(支付|转账|缴费)})+NOT={退款,退回}", priority: 330 },
    DefaultCategoryRule { name: "default:交通出行/打车网约车", main_category: "交通出行", sub_category: "打车网约车", rule_expression: "OR={滴滴,高德打车,曹操出行,T3出行,花小猪,出租车}", priority: 400 },
    DefaultCategoryRule { name: "default:交通出行/公交地铁", main_category: "交通出行", sub_category: "公交地铁", rule_expression: "OR={地铁,公交,交通卡,一卡通,乘车码}", priority: 410 },
    DefaultCategoryRule { name: "default:交通出行/高铁火车", main_category: "交通出行", sub_category: "高铁火车", rule_expression: "OR={铁路12306,12306,火车票,高铁票,动车票}", priority: 420 },
    DefaultCategoryRule { name: "default:交通出行/机票", main_category: "交通出行", sub_category: "机票", rule_expression: "OR={航旅纵横,机票,航空,机场,携程,飞猪,同程,去哪儿}", priority: 430 },
    DefaultCategoryRule { name: "default:交通出行/加油充电", main_category: "交通出行", sub_category: "加油充电", rule_expression: "OR={中石化,中石油,壳牌,加油,充电桩,特来电,星星充电}", priority: 440 },
    DefaultCategoryRule { name: "default:交通出行/停车过路", main_category: "交通出行", sub_category: "停车过路", rule_expression: "OR={停车,ETCP,高速费,过路费,路桥费}", priority: 450 },
    DefaultCategoryRule { name: "default:医疗健康/挂号诊疗", main_category: "医疗健康", sub_category: "挂号诊疗", rule_expression: "OR={医院,诊所,挂号,门诊,急诊,体检,口腔}", priority: 500 },
    DefaultCategoryRule { name: "default:医疗健康/药品", main_category: "医疗健康", sub_category: "药品", rule_expression: "OR={药房,药店,阿里健康,京东健康,叮当快药,药品}", priority: 510 },
    DefaultCategoryRule { name: "default:服饰美妆/护肤彩妆", main_category: "服饰美妆", sub_category: "护肤彩妆", rule_expression: "OR={屈臣氏,丝芙兰,护肤,彩妆,化妆品,美妆}", priority: 600 },
    DefaultCategoryRule { name: "default:数码办公/软件工具", main_category: "数码办公", sub_category: "软件工具", rule_expression: "OR={Apple,App Store,微软,Adobe,JetBrains,Notion,飞书,钉钉,软件,订阅,云服务}", priority: 700 },
    DefaultCategoryRule { name: "default:教育成长/课程培训", main_category: "教育成长", sub_category: "课程培训", rule_expression: "OR={学费,培训,课程,得到,知识星球,考试,报名费,教材}", priority: 800 },
    DefaultCategoryRule { name: "default:娱乐休闲/会员订阅", main_category: "娱乐休闲", sub_category: "会员订阅", rule_expression: "OR={腾讯视频,爱奇艺,优酷,网易云音乐,QQ音乐,B站大会员,Netflix,Spotify,会员,订阅}", priority: 900 },
    DefaultCategoryRule { name: "default:娱乐休闲/游戏", main_category: "娱乐休闲", sub_category: "游戏", rule_expression: "OR={Steam,PlayStation,Nintendo,腾讯游戏,网易游戏,米哈游,游戏}", priority: 910 },
    DefaultCategoryRule { name: "default:旅行住宿/酒店民宿", main_category: "旅行住宿", sub_category: "酒店民宿", rule_expression: "OR={酒店,民宿,携程酒店,飞猪酒店,美团酒店,Booking,Airbnb}", priority: 1000 },
    DefaultCategoryRule { name: "default:人情社交/红包转账", main_category: "人情社交", sub_category: "红包转账", rule_expression: "(OR={红包,礼金,份子钱}/REGEX={(微信|支付宝).*(红包|转账)})+NOT={退款,退回,还款}", priority: 1100 },
    DefaultCategoryRule { name: "default:金融保险/保险", main_category: "金融保险", sub_category: "保险", rule_expression: "OR={保险,保费,众安,平安保险,太平洋保险,医保,社保}", priority: 1200 },
    DefaultCategoryRule { name: "default:金融保险/手续费", main_category: "金融保险", sub_category: "手续费", rule_expression: "OR={手续费,服务费,年费,管理费}", priority: 1210 },
    DefaultCategoryRule { name: "default:工作收入/工资", main_category: "工作收入", sub_category: "工资", rule_expression: "REGEX={(工资|薪资|薪金|工资代发|工资发放)}", priority: 2000 },
    DefaultCategoryRule { name: "default:工作收入/奖金", main_category: "工作收入", sub_category: "奖金", rule_expression: "REGEX={(奖金|绩效|年终奖)}", priority: 2010 },
    DefaultCategoryRule { name: "default:生活收入/退款", main_category: "生活收入", sub_category: "退款", rule_expression: "REGEX={(退款|退货|冲正|原路退回)}", priority: 2300 },
    DefaultCategoryRule { name: "default:工作收入/报销", main_category: "工作收入", sub_category: "报销", rule_expression: "REGEX={报销}", priority: 2310 },
    DefaultCategoryRule { name: "default:账户互转/信用卡还款", main_category: "账户互转", sub_category: "信用卡还款", rule_expression: "OR={信用卡还款,还信用卡}", priority: 3000 },
    DefaultCategoryRule { name: "default:账户互转/银行卡互转", main_category: "账户互转", sub_category: "银行卡互转", rule_expression: "REGEX={(银行卡转入|银行卡转出|转账到银行卡|银行卡入账)}", priority: 3010 },
    DefaultCategoryRule { name: "default:账户互转/余额充值", main_category: "账户互转", sub_category: "余额充值", rule_expression: "REGEX={(充值|余额宝转入|零钱通转入)}", priority: 3020 },
    DefaultCategoryRule { name: "default:账户互转/提现", main_category: "账户互转", sub_category: "提现", rule_expression: "REGEX={(提现|余额宝转出|零钱通转出)}", priority: 3030 },
];

const ZH_DEFAULT_ACCOUNTS: &[DefaultAccountTemplate] = &[
    DefaultAccountTemplate {
        name: "现金",
        type_code: 1,
        category: 1,
        currency: "CNY",
        icon: "1",
        color: "4caf50",
        aliases: &["现金", "现金钱包", "cash"],
        display_order: 0,
    },
    DefaultAccountTemplate {
        name: "借记卡",
        type_code: 1,
        category: 2,
        currency: "CNY",
        icon: "100",
        color: "2196f3",
        aliases: &["借记卡", "储蓄卡", "银行卡", "debit card"],
        display_order: 1,
    },
    DefaultAccountTemplate {
        name: "信用卡",
        type_code: 1,
        category: 3,
        currency: "CNY",
        icon: "100",
        color: "ff9800",
        aliases: &["信用卡", "贷记卡", "credit card"],
        display_order: 2,
    },
    DefaultAccountTemplate {
        name: "支付宝",
        type_code: 1,
        category: 4,
        currency: "CNY",
        icon: "500",
        color: "1677ff",
        aliases: &["支付宝", "alipay", "花呗", "余额宝"],
        display_order: 3,
    },
    DefaultAccountTemplate {
        name: "微信",
        type_code: 1,
        category: 4,
        currency: "CNY",
        icon: "500",
        color: "07c160",
        aliases: &["微信", "微信支付", "wechat"],
        display_order: 4,
    },
];

const DEFAULT_ACCOUNTS: &[DefaultAccountTemplate] = &[
    DefaultAccountTemplate {
        name: "Cash",
        type_code: 1,
        category: 1,
        currency: "CNY",
        icon: "1",
        color: "4caf50",
        aliases: &["cash", "wallet"],
        display_order: 0,
    },
    DefaultAccountTemplate {
        name: "Debit Card",
        type_code: 1,
        category: 2,
        currency: "CNY",
        icon: "100",
        color: "2196f3",
        aliases: &["debit card", "bank card", "checking"],
        display_order: 1,
    },
    DefaultAccountTemplate {
        name: "Credit Card",
        type_code: 1,
        category: 3,
        currency: "CNY",
        icon: "100",
        color: "ff9800",
        aliases: &["credit card"],
        display_order: 2,
    },
    DefaultAccountTemplate {
        name: "Alipay",
        type_code: 1,
        category: 4,
        currency: "CNY",
        icon: "500",
        color: "1677ff",
        aliases: &["alipay"],
        display_order: 3,
    },
    DefaultAccountTemplate {
        name: "WeChat",
        type_code: 1,
        category: 4,
        currency: "CNY",
        icon: "500",
        color: "07c160",
        aliases: &["wechat", "wechat pay"],
        display_order: 4,
    },
];
