CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT,
    display_name TEXT,
    password_hash TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    account_type TEXT,
    payment_method TEXT,
    currency TEXT NOT NULL DEFAULT 'CNY',
    balance_cents BIGINT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, name)
);

COMMENT ON COLUMN accounts.balance_cents IS 'amount stored in cents for the Postgres authoritative runtime';

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    category_type TEXT,
    path TEXT,
    icon TEXT,
    color TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, parent_id, name)
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    color TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    occurred_at TIMESTAMPTZ NOT NULL,
    amount_cents BIGINT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('income', 'expense')),
    transaction_type TEXT NOT NULL DEFAULT 'expense',
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    transfer_target_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    source_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    target_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    merchant TEXT,
    payment_method TEXT,
    description TEXT,
    parser_name TEXT,
    parser_signal TEXT,
    source_hash TEXT,
    duplicate_group_key TEXT,
    standard_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

COMMENT ON COLUMN bills.amount_cents IS 'amount stored in cents; import parsers must convert from source yuan or cent units before insert';

CREATE TABLE IF NOT EXISTS bill_tags (
    bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (bill_id, tag_id)
);

CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value JSONB NOT NULL DEFAULT '{}'::jsonb,
    sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, key)
);

CREATE TABLE IF NOT EXISTS parser_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parser_id TEXT NOT NULL,
    source_name TEXT,
    template_name TEXT,
    feature_signature TEXT NOT NULL,
    parser_version TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, parser_id, feature_signature)
);

CREATE TABLE IF NOT EXISTS category_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    transaction_type_scope TEXT NOT NULL DEFAULT 'all',
    field_scope JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_expression JSONB NOT NULL DEFAULT '{}'::jsonb,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS account_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    account_role_scope TEXT NOT NULL DEFAULT 'any',
    transaction_type_scope TEXT NOT NULL DEFAULT 'all',
    field_scope JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_expression JSONB NOT NULL DEFAULT '{}'::jsonb,
    regex_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    source TEXT NOT NULL DEFAULT 'manual',
    source_key TEXT,
    match_count BIGINT NOT NULL DEFAULT 0,
    last_matched_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS import_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    import_mode TEXT NOT NULL DEFAULT 'preview',
    source_count INTEGER NOT NULL DEFAULT 0,
    row_count INTEGER NOT NULL DEFAULT 0,
    file_count BIGINT NOT NULL DEFAULT 0,
    total_parsed BIGINT NOT NULL DEFAULT 0,
    total_preview BIGINT NOT NULL DEFAULT 0,
    total_confirmed BIGINT NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, session_key)
);

CREATE TABLE IF NOT EXISTS import_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_index INTEGER NOT NULL,
    original_file_name TEXT,
    parser_id TEXT NOT NULL,
    parser_name TEXT NOT NULL,
    parser_signal TEXT,
    parser_confidence NUMERIC(8, 6),
    feature_signature TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (session_id, source_index),
    UNIQUE (session_id, feature_signature)
);

CREATE TABLE IF NOT EXISTS import_standard_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    source_id BIGINT NOT NULL REFERENCES import_sources(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_row_index INTEGER NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    amount_cents BIGINT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('income', 'expense')),
    transaction_type TEXT NOT NULL DEFAULT 'expense',
    merchant TEXT,
    payment_method TEXT,
    description TEXT,
    parser_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    standard_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (source_id, source_row_index)
);

COMMENT ON COLUMN import_standard_rows.amount_cents IS 'amount stored in cents after parser normalization';

CREATE TABLE IF NOT EXISTS import_preview_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    base_standard_row_id BIGINT REFERENCES import_standard_rows(id) ON DELETE SET NULL,
    history_bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    history_bill_version BIGINT,
    page_sort_key TEXT NOT NULL,
    operation_kind TEXT NOT NULL DEFAULT 'insert',
    selected BOOLEAN NOT NULL DEFAULT TRUE,
    signal_summary JSONB NOT NULL DEFAULT '[]'::jsonb,
    merged_source_ids BIGINT[] NOT NULL DEFAULT '{}'::bigint[],
    occurred_at TIMESTAMPTZ NOT NULL,
    amount_cents BIGINT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('income', 'expense')),
    transaction_type TEXT NOT NULL DEFAULT 'expense',
    account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    transfer_target_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    merchant TEXT,
    payment_method TEXT,
    description TEXT,
    hidden_transfer_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    preview_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

COMMENT ON COLUMN import_preview_rows.amount_cents IS 'amount stored in cents for preview and history rewrite operations';

CREATE TABLE IF NOT EXISTS import_decision_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_type TEXT NOT NULL,
    group_key TEXT NOT NULL,
    decision_status TEXT NOT NULL DEFAULT 'pending',
    base_preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE SET NULL,
    signal_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (session_id, group_type, group_key)
);

CREATE TABLE IF NOT EXISTS import_decision_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES import_decision_groups(id) ON DELETE CASCADE,
    preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE CASCADE,
    standard_row_id BIGINT REFERENCES import_standard_rows(id) ON DELETE SET NULL,
    history_bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    member_role TEXT NOT NULL,
    parser_name TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (group_id, preview_row_id, standard_row_id, history_bill_id, member_role)
);

CREATE TABLE IF NOT EXISTS import_history_materializations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    history_bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    history_bill_version BIGINT NOT NULL,
    materialized_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    rewrite_reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (session_id, history_bill_id)
);

CREATE TABLE IF NOT EXISTS import_confirm_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    operation_kind TEXT NOT NULL,
    preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE SET NULL,
    history_bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    created_bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    deleted_bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS matching_pairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    left_bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    right_bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    pair_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    confidence NUMERIC(8, 6),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, pair_type, left_bill_id, right_bill_id)
);

CREATE TABLE IF NOT EXISTS matching_suppressions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    left_bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    right_bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    suppression_key TEXT NOT NULL,
    pair_type TEXT NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, suppression_key)
);

CREATE TABLE IF NOT EXISTS preview_matching_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES import_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES import_decision_groups(id) ON DELETE SET NULL,
    preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE SET NULL,
    feedback_type TEXT NOT NULL,
    decision TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS matching_feedback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    matching_pair_id BIGINT REFERENCES matching_pairs(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL DEFAULT 'user',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_learning_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE SET NULL,
    sample_key TEXT NOT NULL,
    normalized_features JSONB NOT NULL DEFAULT '{}'::jsonb,
    target_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, sample_key)
);

CREATE TABLE IF NOT EXISTS import_learning_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sample_id BIGINT NOT NULL REFERENCES import_learning_samples(id) ON DELETE CASCADE,
    feature_key TEXT NOT NULL,
    feature_hash TEXT NOT NULL,
    feature_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    vector_ref TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, sample_id, feature_key)
);

CREATE TABLE IF NOT EXISTS import_learning_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES import_sessions(id) ON DELETE CASCADE,
    preview_row_id BIGINT REFERENCES import_preview_rows(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recommendation_key TEXT NOT NULL,
    score NUMERIC(8, 6) NOT NULL,
    signal_state TEXT NOT NULL DEFAULT 'yellow',
    suggested_type TEXT,
    suggested_category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    suggested_expense_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    suggested_income_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS import_learning_lifecycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recommendation_key TEXT NOT NULL,
    recommendation_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'yellow',
    accepted_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    auto_applied_count INTEGER NOT NULL DEFAULT 0,
    auto_apply_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    suppressed_until TIMESTAMPTZ,
    last_feedback_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, recommendation_key)
);

CREATE TABLE IF NOT EXISTS import_learning_feedback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rule_id BIGINT,
    suggestion_id BIGINT REFERENCES import_learning_suggestions(id) ON DELETE SET NULL,
    lifecycle_id BIGINT REFERENCES import_learning_lifecycle(id) ON DELETE SET NULL,
    recommendation_key TEXT NOT NULL,
    event_type TEXT NOT NULL,
    session_id TEXT,
    preview_id BIGINT,
    bill_id BIGINT,
    candidate_id TEXT,
    previous_signal_state TEXT,
    next_signal_state TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_learning_suppressions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recommendation_key TEXT NOT NULL,
    suppression_reason TEXT NOT NULL,
    suppressed_until TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, recommendation_key)
);

CREATE TABLE IF NOT EXISTS learning_threshold_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_name TEXT NOT NULL,
    recommendation_type TEXT NOT NULL,
    yellow_threshold NUMERIC(8, 6) NOT NULL,
    green_threshold NUMERIC(8, 6) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, profile_name, recommendation_type)
);

CREATE TABLE IF NOT EXISTS business_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor TEXT NOT NULL DEFAULT 'runtime',
    before_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vector_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS migration_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_name TEXT NOT NULL,
    stage TEXT NOT NULL,
    status TEXT NOT NULL,
    source_backend TEXT NOT NULL DEFAULT 'postgres',
    target_backend TEXT NOT NULL DEFAULT 'postgres',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bills_user_time_amount_direction
    ON bills (user_id, occurred_at, amount_cents, direction);
CREATE INDEX IF NOT EXISTS idx_bills_user_updated
    ON bills (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_accounts_user_lookup
    ON accounts (user_id, name);
CREATE INDEX IF NOT EXISTS idx_categories_user_lookup
    ON categories (user_id, parent_id, name);
CREATE INDEX IF NOT EXISTS idx_tags_user_lookup
    ON tags (user_id, name);
CREATE INDEX IF NOT EXISTS idx_category_rules_user_enabled_type_priority
    ON category_rules (user_id, enabled, transaction_type_scope, priority DESC, id);
CREATE INDEX IF NOT EXISTS idx_account_rules_user_enabled_type_priority
    ON account_rules (user_id, enabled, transaction_type_scope, account_role_scope, priority, id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_account_rules_alias_source_unique
    ON account_rules (user_id, account_id, source, source_key)
    WHERE source_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_import_preview_rows_session_page_sort_key
    ON import_preview_rows (session_id, page_sort_key, id);
CREATE INDEX IF NOT EXISTS idx_import_decision_groups_session_group_type
    ON import_decision_groups (session_id, group_type);
CREATE INDEX IF NOT EXISTS idx_import_decision_group_members_group
    ON import_decision_group_members (group_id, member_role);
CREATE INDEX IF NOT EXISTS idx_import_history_materializations_session_history_bill
    ON import_history_materializations (session_id, history_bill_id);
CREATE INDEX IF NOT EXISTS idx_matching_pairs_user_status
    ON matching_pairs (user_id, status, pair_type);
CREATE INDEX IF NOT EXISTS idx_matching_suppressions_user_pair
    ON matching_suppressions (user_id, pair_type, left_bill_id, right_bill_id);
CREATE INDEX IF NOT EXISTS idx_import_learning_lifecycle_user_recommendation_key
    ON import_learning_lifecycle (user_id, recommendation_key);
CREATE INDEX IF NOT EXISTS idx_import_learning_feedback_events_user_key
    ON import_learning_feedback_events (user_id, recommendation_key, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_learning_feedback_events_user_type
    ON import_learning_feedback_events (user_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vector_outbox_events_status_available_at
    ON vector_outbox_events (status, available_at);
CREATE INDEX IF NOT EXISTS idx_business_audit_events_user_entity_created
    ON business_audit_events (user_id, entity_type, entity_id, created_at DESC);
