CREATE TABLE IF NOT EXISTS transaction_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_type INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL,
    description TEXT,
    transaction_type TEXT,
    category_id TEXT,
    source_account_id TEXT,
    destination_account_id TEXT,
    source_amount_minor_units DOUBLE PRECISION NOT NULL DEFAULT 0,
    destination_amount_minor_units DOUBLE PRECISION NOT NULL DEFAULT 0,
    hide_amount BOOLEAN NOT NULL DEFAULT FALSE,
    tag_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    comment TEXT,
    scheduled_frequency_type INTEGER,
    scheduled_frequency TEXT,
    scheduled_start_date TEXT,
    scheduled_end_date TEXT,
    scheduled_next_date TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    auto_create BOOLEAN NOT NULL DEFAULT FALSE,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    use_count BIGINT NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    display_order INTEGER NOT NULL DEFAULT 0,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    utc_offset INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, template_type, name)
);

COMMENT ON COLUMN transaction_templates.source_amount_minor_units IS 'template amount value in exact minor units';
COMMENT ON COLUMN transaction_templates.destination_amount_minor_units IS 'destination amount value in exact minor units';

CREATE INDEX IF NOT EXISTS idx_transaction_templates_user_type_order
    ON transaction_templates (user_id, template_type, display_order, name);
