CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT,
    sub_category TEXT NOT NULL DEFAULT '',
    period_type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    start_date DATE NOT NULL,
    end_date DATE,
    alert_threshold INTEGER NOT NULL DEFAULT 80,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

COMMENT ON COLUMN budgets.amount_cents IS 'budget amount stored in cents';

CREATE INDEX IF NOT EXISTS idx_budgets_user_period_category
    ON budgets (user_id, period_type, enabled, category, start_date DESC);
