CREATE TABLE IF NOT EXISTS budget_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    budget_id BIGINT NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    budget_amount_cents BIGINT NOT NULL DEFAULT 0,
    spent_amount_cents BIGINT NOT NULL DEFAULT 0,
    remaining_amount_cents BIGINT NOT NULL DEFAULT 0,
    execution_rate NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'within_budget',
    filter_summary TEXT NOT NULL DEFAULT '',
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, budget_id, period_start, period_end, filter_summary)
);

COMMENT ON COLUMN budget_history.budget_amount_cents IS 'budget amount stored in cents for PostgreSQL budget execution snapshots';
COMMENT ON COLUMN budget_history.spent_amount_cents IS 'spent amount stored in cents for PostgreSQL budget execution snapshots';
COMMENT ON COLUMN budget_history.remaining_amount_cents IS 'remaining amount stored in cents for PostgreSQL budget execution snapshots';

CREATE INDEX IF NOT EXISTS idx_budget_history_user_budget_period
    ON budget_history (user_id, budget_id, period_start DESC, period_end DESC);

CREATE INDEX IF NOT EXISTS idx_budget_history_user_filter_period
    ON budget_history (user_id, filter_summary, period_start DESC, period_end DESC);
