CREATE TABLE IF NOT EXISTS recurring_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    pattern_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    source_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    destination_account_id BIGINT REFERENCES accounts(id) ON DELETE SET NULL,
    counterparty TEXT,
    frequency TEXT NOT NULL,
    detected_interval_days NUMERIC(10, 2),
    confidence_score NUMERIC(8, 6) NOT NULL DEFAULT 0,
    sample_count INTEGER NOT NULL DEFAULT 0,
    sample_bill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    first_occurrence TEXT,
    last_occurrence TEXT,
    suggested_next_date TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, pattern_hash)
);

COMMENT ON COLUMN recurring_suggestions.amount_cents IS 'amount stored in cents; API responses project this value back to frontend yuan amount';

CREATE INDEX IF NOT EXISTS idx_recurring_suggestions_user_status
    ON recurring_suggestions (user_id, status, confidence_score DESC, last_occurrence DESC);
