CREATE TABLE IF NOT EXISTS user_external_auths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    external_auth_category TEXT NOT NULL,
    external_auth_type TEXT NOT NULL,
    external_user_id TEXT,
    external_username TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, external_auth_type)
);

CREATE INDEX IF NOT EXISTS idx_user_external_auths_user
    ON user_external_auths(user_id);

CREATE INDEX IF NOT EXISTS idx_user_external_auths_type
    ON user_external_auths(external_auth_type);
