CREATE TABLE IF NOT EXISTS backup_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_name TEXT NOT NULL UNIQUE,
    storage_type TEXT NOT NULL DEFAULT 'local',
    file_path TEXT NOT NULL,
    checksum TEXT,
    encrypted BOOLEAN NOT NULL DEFAULT false,
    status TEXT NOT NULL DEFAULT 'created',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS backup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_type TEXT NOT NULL,
    schedule_expr TEXT NOT NULL DEFAULT '',
    retention_days BIGINT NOT NULL DEFAULT 30,
    retention_count BIGINT NOT NULL DEFAULT 10,
    enabled BOOLEAN NOT NULL DEFAULT true,
    last_run_at TIMESTAMPTZ,
    last_status TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, job_type)
);

CREATE TABLE IF NOT EXISTS backup_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type TEXT NOT NULL,
    operation_target TEXT NOT NULL DEFAULT 'backup',
    target_id BIGINT,
    details JSONB,
    affected_count BIGINT NOT NULL DEFAULT 0,
    ip_address TEXT,
    user_agent TEXT,
    session_id TEXT,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backup_records_status_created
    ON backup_records(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_backup_jobs_type_enabled
    ON backup_jobs(job_type, enabled);

CREATE INDEX IF NOT EXISTS idx_backup_jobs_user_type_enabled
    ON backup_jobs(user_id, job_type, enabled);

CREATE INDEX IF NOT EXISTS idx_backup_audit_logs_type
    ON backup_audit_logs(operation_type, created_at);

CREATE INDEX IF NOT EXISTS idx_backup_audit_logs_target
    ON backup_audit_logs(operation_target, target_id);

CREATE INDEX IF NOT EXISTS idx_backup_audit_logs_created
    ON backup_audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_backup_audit_logs_status
    ON backup_audit_logs(status);
