CREATE TABLE IF NOT EXISTS llm_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT 'openai',
    model TEXT NOT NULL DEFAULT '',
    api_key TEXT NOT NULL DEFAULT '',
    base_url TEXT NOT NULL DEFAULT '',
    credential_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    advanced_settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_llm_configs_user_active
    ON llm_configs (user_id, is_active, updated_at DESC);

CREATE TABLE IF NOT EXISTS llm_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'classification',
    source_bill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    suggested_main_category TEXT NOT NULL DEFAULT '',
    suggested_sub_category TEXT NOT NULL DEFAULT '',
    suggested_rule_expression TEXT NOT NULL DEFAULT '',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    llm_provider TEXT NOT NULL DEFAULT '',
    llm_model TEXT NOT NULL DEFAULT '',
    llm_response_raw TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_llm_candidates_user_status
    ON llm_candidates (user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS llm_memory_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT,
    preview_id BIGINT,
    event_type TEXT NOT NULL,
    decision TEXT,
    prompt_text TEXT,
    llm_response_raw TEXT,
    llm_provider TEXT,
    llm_model TEXT,
    suggested_main_category TEXT,
    suggested_sub_category TEXT,
    suggested_source_account TEXT,
    suggested_destination_account TEXT,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    user_correction_category TEXT,
    user_correction_account TEXT,
    snapshot_before JSONB,
    snapshot_after JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_llm_memory_events_user_created
    ON llm_memory_events (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS import_annotation_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    preview_id BIGINT,
    annotation_type TEXT NOT NULL,
    annotation_key TEXT NOT NULL,
    sample_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1,
    UNIQUE (user_id, session_id, annotation_type, annotation_key)
);

CREATE INDEX IF NOT EXISTS idx_import_annotation_samples_user_session
    ON import_annotation_samples (user_id, session_id, annotation_type);
